version: "3"

services:
    loki:
        image: grafana/loki:master
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - "3100:3100"
        networks:
            - world
            - grafana-loki
        labels:
            - com.cossacklabs.acra-telemetry-collector=loki

    prometheus:
        # Build and run the container based on the official image 
        # Add additional configuration from here. 
        # Use environment variables declared earlier to extend configuration of prometheus 
        build:
            context: .
            dockerfile: prometheus/dockerfile

        ports:
            - "9090:9090"

        environment:
            PROMETHEUS_TARGETS: ${PROMETHEUS_TARGETS:-"104.248.202.177:9399"}
        networks:
            - world
            - grafana-prometheus

    grafana:
        depends_on:
            - loki
        image: grafana/grafana:8.3.3
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: test
            GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
        volumes:
            - ./grafana:/app.cfg
            - ./grafana/plugins:/var/lib/grafana/plugins
        networks:
            - world
            - grafana-loki
            - grafana-prometheus
        labels:
            - com.cossacklabs.acra-telemetry-collector=grafana

networks:
    world: null
    grafana-loki:
        internal: true
    grafana-prometheus:
        internal: true
