version: "3"

services:
    loki:
        image: grafana/loki:master
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - "3100:3100"
        networks:
            - world
            - grafana-loki

    prometheus:
        image: prom/prometheus:v2.32.1
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/app.cfg
        networks:
            - world
            - grafana-prometheus
        command: >-
            --config.file=/app.cfg/prometheus.yml --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles

    grafana:
        depends_on:
            - loki
        image: grafana/grafana:8.3.3
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: test
            GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
        volumes:
            - ./grafana:/app.cfg
        networks:
            - world
            - grafana-loki
            - grafana-prometheus

    jaeger:
        image: jaegertracing/all-in-one:1.29
        ports:
            - "16686:16686"
        networks:
            - world
            - jaeger

networks:
    world: null
    grafana-loki:
        internal: true
    grafana-prometheus:
        internal: true
    jaeger:
        internal: true
