FROM prom/prometheus:v2.32.1
LABEL com.cossacklabs.acra-telemetry-collector=prometheus 

USER root 
RUN mkdir /app.cfg 
COPY prometheus/prometheus.yml /app.cfg/
COPY prometheus/entry.sh /

ENTRYPOINT [ "/entry.sh" ]