{
 "title": "Acra Server Logging Dashboard",
 "description": "Acra Server Logging Dashboard",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container",
    "query": "label_values({container_name=~\".+\"}, container_name)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "singlestat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "singlestat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{container_name=\"$container_name\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"})[$__interval])) by (container_name)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (container_name)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container_name=\"$container_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (container_name)"
    }
   ]
  }
 ]
}