{
 "title": "AcraServer",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "pctl", "label": "Percentile", "query": "50,90,95,99" },
   { "name": "win", "label": "Window", "query": "30s, 1m, 2m, 5m, 10m" }
  ]
 },
 "panels": [
  {
   "title": "AcraServer : connection rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(acraserver_connections_total[$win])",
     "legendFormat": "{{ connection_type }}"
    }
   ]
  },
  {
   "title": "AcraServer : connection lifetime (percentile $pctl)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$pctl, sum(rate(acraserver_connections_processing_seconds_bucket[$win])) by (connection_type,le))",
     "legendFormat": "{{ connection_type }}"
    }
   ]
  },
  {
   "title": "AcraServer : request processing time (percentile $pctl)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$pctl, sum(rate(acraserver_request_processing_seconds_bucket[$win])) by (le))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "AcraServer : response processing time (percentile $pctl)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$pctl, sum(rate(acraserver_response_processing_seconds_bucket[$win])) by (le))",
     "legendFormat": "responses"
    }
   ]
  },
  {
   "title": "AcraServer Memory (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"acra-server\"}"
    }
   ]
  },
  {
   "title": "AcraServer CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"acra-server\"}[$__interval])"
    }
   ]
  }
 ]
}